data_load:
  input_directory: '../data/'
  noise: 'AX_Flair_Clear.nii.gz'
  truth: 'T2_Flair_Sense.nii.gz'
  by_slice: True

data_save:
  modelname: '.epochs.20.batch.1.cost.MSE.'
  outputdir: '../checkpoints/MSE/'

model:
  epochs: 20
  loss_function: 'mean_squared_error'
  
  batch_norm: True
  batch_size: 1
  validation_split: 0.1
  
  num_poolings: 3
  num_conv_per_pooling: 3

  lr_init: 0.001
