data_load:
  input_directory: '../data/'
  noise: 'AX_Flair_Clear.nii.gz'
  truth: 'T2_Flair_Sense.nii.gz'
  by_slice: True

data_save:
  modelname: 'epochs.20.cost.KL'
  outputdir: '../checkpoints/KL/'

model:
  epochs: 20
  loss_function: 'kullback_leibler_divergence'
  
  batch_norm: True
  batch_size: 4
  validation_split: 0.1
  
  num_poolings: 3
  num_conv_per_pooling: 3

  lr_init: 0.001
