data_load:
  files:
    source1:
      truth: '../data/subj_1/T2_Flair_Sense.nii.gz'
      noise: '../data/subj_1/AX_Flair_Clear.nii.gz'
    source2:
      truth: '../data/subj_2/T2_Flair_Sense.nii.gz'
      noise: '../data/subj_2/AX_Flair_Clear.nii.gz'
  by_slice: True

data_save:
  modelname: '.epochs.20.cost.KL.'
  outputdir: '../checkpoints/KL/'

model:
  epochs: 20
  loss_function: 'kullback_leibler_divergence'
  
  batch_norm: True
  batch_size: 4
  validation_split: 0.1
  
  num_poolings: 3
  num_conv_per_pooling: 3

  lr_init: 0.001
